job_name = "CI"
license = "MIT/Apache-2.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
documentation = "{{docs_rs}}/{{crate.name}}"
default_workflow = "data/default_workflow.yml"

[extra]
github = "https://github.com"
docs_rs = "https://docs.rs"
docs_rs_image = "data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDUxMiA1MTIiPjxwYXRoIGZpbGw9IiNmNWY1ZjUiIGQ9Ik00ODguNiAyNTAuMkwzOTIgMjE0VjEwNS41YzAtMTUtOS4zLTI4LjQtMjMuNC0zMy43bC0xMDAtMzcuNWMtOC4xLTMuMS0xNy4xLTMuMS0yNS4zIDBsLTEwMCAzNy41Yy0xNC4xIDUuMy0yMy40IDE4LjctMjMuNCAzMy43VjIxNGwtOTYuNiAzNi4yQzkuMyAyNTUuNSAwIDI2OC45IDAgMjgzLjlWMzk0YzAgMTMuNiA3LjcgMjYuMSAxOS45IDMyLjJsMTAwIDUwYzEwLjEgNS4xIDIyLjEgNS4xIDMyLjIgMGwxMDMuOS01MiAxMDMuOSA1MmMxMC4xIDUuMSAyMi4xIDUuMSAzMi4yIDBsMTAwLTUwYzEyLjItNi4xIDE5LjktMTguNiAxOS45LTMyLjJWMjgzLjljMC0xNS05LjMtMjguNC0yMy40LTMzLjd6TTM1OCAyMTQuOGwtODUgMzEuOXYtNjguMmw4NS0zN3Y3My4zek0xNTQgMTA0LjFsMTAyLTM4LjIgMTAyIDM4LjJ2LjZsLTEwMiA0MS40LTEwMi00MS40di0uNnptODQgMjkxLjFsLTg1IDQyLjV2LTc5LjFsODUtMzguOHY3NS40em0wLTExMmwtMTAyIDQxLjQtMTAyLTQxLjR2LS42bDEwMi0zOC4yIDEwMiAzOC4ydi42em0yNDAgMTEybC04NSA0Mi41di03OS4xbDg1LTM4Ljh2NzUuNHptMC0xMTJsLTEwMiA0MS40LTEwMi00MS40di0uNmwxMDItMzguMiAxMDIgMzguMnYuNnoiPjwvcGF0aD48L3N2Zz4K"
badge_colors = { github = "8da0cb", crates_io = "fc8d62", docs_rs = "66c2a5" }
badge_height = 20

[[badges]]
alt = "github"
src = "https://img.shields.io/badge/github-{{dash_escape crate.repo}}-{{badge_colors.github}}?style=for-the-badge&logo=github"
href = "{{github}}/{{crate.repo}}"
height = "{{badge_height}}"

[[badges]]
alt = "crates.io"
src = "https://img.shields.io/crates/v/{{crate.name}}.svg?style=for-the-badge&color={{badge_colors.crates_io}}&logo=rust"
href = "https://crates.io/crates/{{crate.name}}"
height = "{{badge_height}}"

[[badges]]
alt = "docs.rs"
src = "https://img.shields.io/badge/docs.rs-{{dash_escape crate.name}}-{{badge_colors.docs_rs}}?style=for-the-badge&logoColor=white&logo={{docs_rs_image}}"
href = "{{docs_rs}}/{{crate.name}}"
height = "{{badge_height}}"

[[badges]]
alt = "build status"
src = "https://img.shields.io/github/actions/workflow/status/{{crate.repo}}/ci.yml?branch=main&style=for-the-badge"
href = "{{github}}/{{crate.repo}}/actions?query=branch%3Amain"
height = "{{badge_height}}"

[repos."repos/aiocp"]
crate = "iocp"

[repos."repos/quickcfg"]
disabled = ["ci"]

[repos."repos/rune"]
header = """
<div align="center">
{{#each badges}}
    {{literal this.html}}
{{/each}}
</div>

<br>

<div align="center">
    <a href="https://rune-rs.github.io"><b>Visit the site üåê</b></a>
    &mdash;
    <a href="https://rune-rs.github.io/book/"><b>Read the book üìñ</b></a>
</div>

<br>

<div align="center">
    <img alt="rune logo" src="https://raw.githubusercontent.com/rune-rs/rune/main/assets/icon.png" />
</div>

<br>

{{description}}
{{#if is_more}}

<br>
{{/if}}
"""

[[repos."repos/rune".badges]]
alt = "chat on discord"
src = "https://img.shields.io/discord/558644981137670144.svg?logo=discord&style=flat-square"
href = "https://discord.gg/v5AeNkT"
height = "{{badge_height}}"
